name: Security
on:
    push:
    
jobs:
    grype:
        name: grype
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Scan
              uses: anchore/scan-action@v3
              id: scan
              with:
                path: "."
                # fail-build: false
                output-format: table
            # - name: upload Anchore scan SARIF report
            #   uses: github/codeql-action/upload-sarif@v3
            #   with:
            #     sarif_file: ${{ steps.scan.outputs.sarif }}